### ISSUE TITLE
Error: module "hugo-classless-netlifycms" not found

### ISSUE THREAD

**Issue by RoneoOrg** [cathelijne/hugo-huguette-example#1]
Hi there,

I'm interested in active themes featuring netlify-cms, so I gave a try this way:

    git clone https://github.com/cathelijne/hugo-huguette-example.git
    cd hugo-huguette-example
    cd exampleSite && hugo server --themesDir ../..

Unfortunately, I get this error:

    Error: module "hugo-classless-netlifycms" not found; either add it as a Hugo Module or store it

Am I missing something?

**Comment by cathelijne** [comment]
I am moving around stuff a lot... Currently on holiday. I should have the theme and a demo site with proper documentation up in a day or 10. Shall I give you a ping when it's up?

**Comment by cathelijne** [comment]
Site is now fully functional
